name: Container workflow

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build-container:
        name: Build container
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{secrets.DOCKER_HUB_USERNAME}}
            password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
        
        - name: Build and Push to Docker Hub
          uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: | 
                devinit23/nextwebapp:latest, devinit23/nextwebapp: ${{github.run_number}}
